-- This file was generated by LetItGo.
local name = "letitgo"
local version = "0.9.0"

food = {
    name = name,
    description = "LetItGo automates releases.",
    homepage = "https://github.com/NoUseFreak/letitgo",
    version = version,
    packages = {
        {
            os = "darwin",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/letitgo/releases/download/0.9.0/darwin_amd64.zip",
            sha256 = "a76ccb241d34a4915c490b4ee30e89eb6486d3e912064b5d607e560d6e2aa9ef",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        },
        {
            os = "linux",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/letitgo/releases/download/0.9.0/linux_amd64.zip",
            sha256 = "df43509fc5144d8ea44774e98ae3d9882726ffba369498c240cadaecaee1bc61",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        },
        {
            os = "windows",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/letitgo/releases/download/0.9.0/windows_amd64.zip",
            sha256 = "4f73874b6ac232d5d55394dfadca913abeddfac49a1b0d680075728cb47542a2",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        }
    }
}

