-- This file was generated by LetItGo.
local name = "letitgo"
local version = "0.9.1"

food = {
    name = name,
    description = "LetItGo automates releases.",
    homepage = "https://github.com/NoUseFreak/letitgo",
    version = version,
    packages = {
        {
            os = "darwin",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/letitgo/releases/download/0.9.1/darwin_amd64.zip",
            sha256 = "5d98c841f29f6281254f3e2257101cb57634acc279a35462e7d264a05d344d5c",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        },
        {
            os = "linux",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/letitgo/releases/download/0.9.1/linux_amd64.zip",
            sha256 = "ef679adebaccdaa34a9dcc55e491e40e1cae40fe5b04876ecb05ab5333526404",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        },
        {
            os = "windows",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/letitgo/releases/download/0.9.1/windows_amd64.zip",
            sha256 = "",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        }
    }
}

