-- This file was generated by LetItGo.
local name = "letitgo"
local version = "0.10.0"

food = {
    name = name,
    description = "LetItGo automates releases.",
    homepage = "https://github.com/NoUseFreak/letitgo",
    version = version,
    packages = {
        {
            os = "darwin",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/letitgo/releases/download/0.10.0/darwin_amd64.zip",
            sha256 = "38f6390f81f91f21d71a7a01e4b3bfefc06b9e13413439ea7aa64f944ca4661c",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        },
        {
            os = "linux",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/letitgo/releases/download/0.10.0/linux_amd64.zip",
            sha256 = "1aaf9b2d123bb28215af5508257b6eba7b5c115c3debba36597341749a2b9562",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        },
        {
            os = "windows",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/letitgo/releases/download/0.10.0/windows_amd64.zip",
            sha256 = "",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        }
    }
}

